// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// bindings to the iRacing SDK Client
class IRacingClient {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  IRacingClient(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  IRacingClient.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  bool isConnected() {
    return _isConnected() != 0;
  }

  late final _isConnectedPtr =
      _lookup<ffi.NativeFunction<ffi.Uint8 Function()>>('isConnected');
  late final _isConnected = _isConnectedPtr.asFunction<int Function()>();
}

const int true1 = 1;

const int false1 = 0;
