desc "Deploy a new beta build to Google Play"
lane :beta do
    build_number = number_of_commits()
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--build-number=#{build_number}")
    end

    upload_to_play_store(track: 'beta', aab: '../build/app/outputs/bundle/release/app-release.aab')
end