# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  flutter: circleci/flutter@1.0.1

executors:
  android-flutter:
    docker:
      - image: cirrusci/flutter:2.10.0
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

jobs:
  integration-tests:
    executor: android-flutter
    steps:
      - checkout
      - run: cd app && flutter test ./integration_test
  deploy:
    executor: android-flutter
    steps:
      - checkout
      - run: echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > key.jks
      - run: echo "$PLAY_STORE_UPLOAD_KEY_INFO" | base64 --decode > android/key.properties
      - run: cd android && fastlane deploy

workflows:
    app:
      jobs:
        - flutter/lint:
            app-dir: ./app 
            version: '2.10.0' 
        - flutter/unit_test:
            app-dir: ./app 
            version: '2.10.0' 
        - integration-tests
